package umk.jakuburb.mars.Teraformacja.Marsa.message;

public enum MessageType {
    USER_IN, USER_OUT, USER_ACTIVE, USER_INACTIVE, GAME_CREATED, NULL,

    MESSAGE_SEND,

    CLOCK, RECOVER, ERROR, PLAYER_IN_GAME, GAME_STATE,USER_STATE, MAIN_CARDS,MAIN_CARDS_SAVE, CARDS10, CARDS10_SAVE,
    RESOURCES, CARDS, OTHERS, LEVELS,

    USE_CARD, NEXT_ROUND, PS,

    TEMP_UP, BOARD_TREE,BOARD_CITY, BOARD_OCEAN, PUT_TREE,PUT_CITY, PUT_OCEAN, PLANET, TITLE, PRIZE
}
